{
  "openapi": "3.0.0",
  "info": {
    "title": "Login API",
    "description": "Login module. This is a module in the microservices architecture with user authentication and CRUD.",
    "contact": {
      "email": "kaiqueroberto.pires@gmail.com"
    },
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "http://localhost:8080/",
      "description": "API in development"
    },
    {
      "url": "https://8080-kaiquepires-loginmodule-iukk8a54h49.ws-us85.gitpod.io/",
      "description": "GitPod"
    }
  ],
  "paths": {
    "/api/user/auth": {
      "post": {
        "summary": "Get access token",
        "tags": [
          "Auth"
        ],
        "security": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "$ref": "#/components/schemas/user"
              },
              "examples": {
                "user": {
                  "value": {
                    "name": "User test",
                    "email": "testuser@gmail.com",
                    "password": 123456
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "number"
                    },
                    "accessToken": {
                      "type": "string"
                    }
                  }
                },
                "examples": {
                  "response": {
                    "value": {
                      "status": 200,
                      "accessToken": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoVXNlciI6eyJpZCI6MywibmFtZSI6IlVzZXIgdGVzdCIsImVtYWlsIjoidGVzdHVzZXJAZ21haWwuY29tIn0sImlhdCI6MTY3NTY1ODkyNCwiZXhwIjoxNjc1NzQ1MzI0fQ.3iBLOU7v21BfSb-KCP9KEa70Dl9L_YN9lAbYd6Mk8ls"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/user/register": {
      "post": {
        "summary": "Create user",
        "tags": [
          "User"
        ],
        "security": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "$ref": "#/components/schemas/user"
              },
              "examples": {
                "user": {
                  "value": {
                    "name": "User test",
                    "email": "testuser@gmail.com",
                    "password": "123456"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "number"
                    },
                    "user": {
                      "type": "object",
                      "properties": {
                        "name": {
                          "type": "string"
                        },
                        "email": {
                          "type": "string"
                        },
                        "password": {
                          "type": "string"
                        }
                      }
                    }
                  }
                },
                "examples": {
                  "response": {
                    "value": {
                      "status": 200,
                      "user": {
                        "id": 1,
                        "name": "User test",
                        "email": "testuser@gmail.com"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/user/{email}": {
      "get": {
        "summary": "Read user by email",
        "tags": [
          "User"
        ],
        "security": [
          {
            "api_key": []
          }
        ],
        "parameters": [
          {
            "name": "email",
            "description": "Logged-in user's email, this route only returns data from the logged-in user",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "number"
                    },
                    "user": {
                      "type": "object"
                    }
                  }
                },
                "examples": {
                  "response": {
                    "value": {
                      "status": 200,
                      "user": {
                        "id": 1,
                        "name": "User test",
                        "email": "testuser@gmail.com"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/user/": {
      "patch": {
        "summary": "Update user",
        "tags": [
          "User"
        ],
        "security": [
          {
            "api_key": []
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "$ref": "#/components/schemas/user"
              },
              "examples": {
                "user": {
                  "value": {
                    "name": "User update",
                    "email": "updateuser@gmail.com",
                    "password": "654321"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "number"
                    },
                    "user": {
                      "type": "object",
                      "properties": {
                        "name": {
                          "type": "string"
                        },
                        "email": {
                          "type": "string"
                        },
                        "password": {
                          "type": "string"
                        }
                      }
                    }
                  }
                },
                "examples": {
                  "user": {
                    "value": {
                      "status": 200,
                      "user": {
                        "id": 1,
                        "name": "User update",
                        "email": "updateuser@gmail.com"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/user/delete": {
      "delete": {
        "summary": "Delete user",
        "tags": [
          "User"
        ],
        "security": [
          {
            "api_key": []
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "number"
                    },
                    "message": {
                      "type": "string"
                    }
                  }
                },
                "examples": {
                  "response": {
                    "value": {
                      "status": 200,
                      "message": "Successful Deleted User"
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "securitySchemes": {
      "api_key": {
        "type": "apiKey",
        "name": "authorization",
        "in": "header"
      }
    },
    "schemas": {
      "user": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "password": {
            "type": "number"
          }
        }
      }
    }
  }
}